[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
OutputDirectory=work/rootfs

[Content]
ExtraTrees=overlay
Autologin=yes
RootPassword=
Timezone=UTC
Keymap=us
Locale=C.UTF-8
Packages=
    kernel
    kernel-modules
    kernel-modules-extra
    linux-firmware
    systemd
    NetworkManager
    sudo
    bash-completion
    zstd
    curl
    ca-certificates
    git
    dracut-live
    kmod

[Build]
WithNetwork=true
Incremental=yes
CacheDirectory=cache
