[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
OutputDirectory=work/rootfs

[Content]
ExtraTrees=overlay
Autologin=yes
RootPassword=

Packages=
    kernel
    kernel-modules
    kernel-modules-extra
    linux-firmware
    systemd
    NetworkManager
    sudo
    bash-completion
    zstd
    curl
    ca-certificates
    git
    kmod
    util-linux
    dracut
    dracut-live

[Build]
WithNetwork=true
Incremental=yes
CacheDirectory=cache
